export const baseUrl="http://alb-ci1p69oty1wtv6wjxl.cn-hangzhou.alb.aliyuncs.com/api"
// export const baseUrl = "http://localhost:8080/api"
// wx.getAccountInfoSync().miniProgram.envVersion == "release"
// export const baseUrl = "http://alb-ci1p69oty1wtv6wjxl.cn-hangzhou.alb.aliyuncs.com/api"
export const userInfoPath = "/userInfos"
export const loginPath = userInfoPath + "/login"
export const joinApplicationPath = "/joinApplications"
export const sendJoinApplicationEmailPath = "/emails/joinApplication/send"
