export const baseUrl = "http://localhost:8080/api"
export const userInfoPath = "/userInfos"
export const loginPath = userInfoPath + "/login"
export const joinApplicationPath = "/joinApplications"
export const sendJoinApplicationEmailPath = "/emails/joinApplication/send"
